In [1]:
# Import our dependencies
import pandas as pd
import numpy as np

In [2]:
# Load the movie_metadata.csv dataset.
file_path = "movie_metadata.csv"
moviedata = pd.read_csv(file_path, index_col=0)
moviedata

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
color,,,,,,,,,,,,,,,,,,,,,
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [3]:
# Check columns
moviedata.columns

Index(['director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [4]:
# Check data type
moviedata.dtypes

director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [8]:
# select the revelant columns
moviedata_df = moviedata[["director_name", "num_critic_for_reviews", "duration", "budget", "gross", "genres", "imdb_score" ]]
moviedata_df

,director_name,num_critic_for_reviews,duration,budget,gross,genres,imdb_score
color,,,,,,,
Color,James Cameron,723.0,178.0,237000000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,7.9
Color,Gore Verbinski,302.0,169.0,300000000.0,309404152.0,Action|Adventure|Fantasy,7.1
Color,Sam Mendes,602.0,148.0,245000000.0,200074175.0,Action|Adventure|Thriller,6.8
Color,Christopher Nolan,813.0,164.0,250000000.0,448130642.0,Action|Thriller,8.5
NaN,Doug Walker,NaN,NaN,NaN,NaN,Documentary,7.1
...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,NaN,NaN,Comedy|Drama,7.7
Color,NaN,43.0,43.0,NaN,NaN,Crime|Drama|Mystery|Thriller,7.5
Color,Benjamin Roberds,13.0,76.0,1400.0,NaN,Drama|Horror|Thriller,6.3
Color,Daniel Hsia,14.0,100.0,NaN,10443.0,Comedy|Drama|Romance,6.3
Color,Jon Gunn,43.0,90.0,1100.0,85222.0,Documentary,6.6

In [9]:
# Remove the "genres" column. 
moviedata_df = moviedata_df.drop(['genres'], axis=1)
moviedata_df.head()

,director_name,num_critic_for_reviews,duration,budget,gross,imdb_score
color,,,,,,
Color,James Cameron,723.0,178.0,237000000.0,760505847.0,7.9
Color,Gore Verbinski,302.0,169.0,300000000.0,309404152.0,7.1
Color,Sam Mendes,602.0,148.0,245000000.0,200074175.0,6.8
Color,Christopher Nolan,813.0,164.0,250000000.0,448130642.0,8.5
NaN,Doug Walker,NaN,NaN,NaN,NaN,7.1

In [10]:
# Remove rows that have at least 1 null value.
moviedata_df = moviedata_df.dropna()
moviedata_df

,director_name,num_critic_for_reviews,duration,budget,gross,imdb_score
color,,,,,,
Color,James Cameron,723.0,178.0,237000000.0,760505847.0,7.9
Color,Gore Verbinski,302.0,169.0,300000000.0,309404152.0,7.1
Color,Sam Mendes,602.0,148.0,245000000.0,200074175.0,6.8
Color,Christopher Nolan,813.0,164.0,250000000.0,448130642.0,8.5
Color,Andrew Stanton,462.0,132.0,263700000.0,73058679.0,6.6
...,...,...,...,...,...,...
Color,Shane Carruth,143.0,77.0,7000.0,424760.0,7.0
Color,Neill Dela Llana,35.0,80.0,7000.0,70071.0,6.3
Color,Robert Rodriguez,56.0,81.0,7000.0,2040920.0,6.9
Color,Edward Burns,14.0,95.0,9000.0,4584.0,6.4
Color,Jon Gunn,43.0,90.0,1100.0,85222.0,6.6

In [12]:
# Keep the rows where coins are mined.
moviedata_df = moviedata_df[moviedata_df['imdb_score'] > 5.0]
moviedata_df

,director_name,num_critic_for_reviews,duration,budget,gross,imdb_score
color,,,,,,
Color,James Cameron,723.0,178.0,237000000.0,760505847.0,7.9
Color,Gore Verbinski,302.0,169.0,300000000.0,309404152.0,7.1
Color,Sam Mendes,602.0,148.0,245000000.0,200074175.0,6.8
Color,Christopher Nolan,813.0,164.0,250000000.0,448130642.0,8.5
Color,Andrew Stanton,462.0,132.0,263700000.0,73058679.0,6.6
...,...,...,...,...,...,...
Color,Shane Carruth,143.0,77.0,7000.0,424760.0,7.0
Color,Neill Dela Llana,35.0,80.0,7000.0,70071.0,6.3
Color,Robert Rodriguez,56.0,81.0,7000.0,2040920.0,6.9
Color,Edward Burns,14.0,95.0,9000.0,4584.0,6.4
Color,Jon Gunn,43.0,90.0,1100.0,85222.0,6.6